[package]
name = "soundtrack_splitter"
version = "0.1.0"
authors = ["John Hörnvall <john.minecraft@hotmail.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simplemad = "0.9.0"
hound = "3.4.0"
